### ISSUE TITLE
can't run in iPhone 64 bit

### ISSUE THREAD

**Issue by ambas** [littleluren/kxmovie#2]
it work find when i run in iPhone 5 but when i try to run in iPhone 5s, i got an error 

Undefined symbols for architecture x86_64:
  "_KxMovieParameterDisableDeinterlacing", referenced from:

or i missing something.

Thank.

**Comment by Guoxweii** [comment]
this version don't support  x86_64 simulator [ IPhone(5s, 6, 6plus), IPad Air ]

**Comment by ambas** [comment]
Thank :)

**Comment by amansharma2014** [comment]
can you tell me about current version which does not have this problem
